// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoreMSIdentity.Data;

#nullable disable

namespace RestoreMSIdentity.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250204190711_SeedSitesData")]
    partial class SeedSitesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoreMSIdentity.Models.SiteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First site",
                            ImageUrl = "https://example.com/image1.jpg",
                            Name = "Site A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second site",
                            ImageUrl = "https://example.com/image2.jpg",
                            Name = "Site B"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third site",
                            ImageUrl = "https://example.com/image3.jpg",
                            Name = "Site C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
